// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrv8mqaNMY0bJYoMlVFIsAyGJCCZlVTN8',
    appId: '1:377332053546:android:69724c93c7db1843a07553',
    messagingSenderId: '377332053546',
    projectId: 'edu-affairs-dev',
    storageBucket: 'edu-affairs-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2OC7Bw3mO6EHdlZgT5jqoK5GT_5R3vM',
    appId: '1:377332053546:ios:aba088a9e3455f1da07553',
    messagingSenderId: '377332053546',
    projectId: 'edu-affairs-dev',
    storageBucket: 'edu-affairs-dev.firebasestorage.app',
    iosClientId: '377332053546-ceib1oavsok9pl2cpp6tufm9l43mrdof.apps.googleusercontent.com',
    iosBundleId: 'com.takween.edu.mobileParent',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEx6x-mKcW97xlw2eFiknFHAIsGY-WTIw',
    appId: '1:377332053546:web:879b85af94eb96fca07553',
    messagingSenderId: '377332053546',
    projectId: 'edu-affairs-dev',
    authDomain: 'edu-affairs-dev.firebaseapp.com',
    storageBucket: 'edu-affairs-dev.firebasestorage.app',
    measurementId: 'G-MR0YQJ9DG2',
  );

}